spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/quickjob_db
        username: Jhousef
        password: 020496231097
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true
