spring:
  security:
    user:
      name: admin
      password: 5c777d74-f9a0-4030-bdd3-a633aa0f5c6f
  datasource:
    url: jdbc:postgresql://localhost:5432/quickjobs_db
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true



#server:
#  port: 8080
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/quickjobs_db
#    username: admin
#    password: 12345

