###add publication
POST http://localhost:8080/api/publication/1/comments
Content-Type: application/json
Accept: application/json

{
  "name": "Commentario Excelente",
  "email": "joshep@gmail.com",
  "body": "Muy bien"
}

###get all publications
GET http://localhost:8080/api/publication/1/comments
Content-Type: application/json
Accept: application/json

###get all publications
GET http://localhost:8080/api/publication/1/comments/2
Content-Type: application/json
Accept: application/json


###get publications by id
GET http://localhost:8080/api/publication/1
Content-Type: application/json
Accept: application/json

###update publication by id
PUT http://localhost:8080/api/publication/1/comments/2
Content-Type: application/json
Accept: application/json

{
  "name": "Commentario perfecto",
  "email": "joshep@gmail.com",
  "body": "Muy bien"
}

###Delete publications by id
DELETE http://localhost:8080/api/publication/5
Content-Type: application/json
Accept: application/json

