##### LISTAR USUARIOS: esta ruta lista los usuarios en formato "json".
GET http://localhost:8080/api/auth/read
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2FjaCIsImlhdCI6MTY3OTkwOTc4OSwiZXhwIjoxNjc5OTA5ODg5fQ.PcTOcWdQHJDEcrWveuTfwCJ6wA-1EYh3di8ujFCAAoTPeh33jOP-GL7KxISSoxXgzSFhnqq2pZmiw5_gvCo7hA

##### CREAR UN USUARIO: esta ruta crea un usuario con datos en formato "json".
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "coach",
    "email": "coach@email.com",
    "password": "Password123!",
    "role": ["admin"]
}

##### ACTUALIZAR UN USUARIO: esta ruta actualiza un usuario con datos en formato "json".
PUT http://localhost:8080/api/auth/update/1
Content-Type: application/json

{
    "username": "coach",
    "email": "coach@email.com",
    "password": "Password123!",
    "role": ["coach"]
}

##### BORRAR O ACTIVAR USUARIOS: esta ruta borra o actualiza un usuario.
DELETE http://localhost:8080/api/auth/delete/1
Content-Type: application/json

##### CREAR UN USUARIO: esta ruta crea un usuario con datos en formato "json".
POST http:// 192.168.100.194:8080/api/auth/signin
Content-Type: application/json

{
  "username": "coach",
  "password": "Password123!"
}



##### AUTENTICAR UN USUARIO: esta ruta autentica un usuario con datos en formato "json".
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username": "mery1",
    "password": "123123.Mery!"
}

##### ACTUALIZAR TOKEN: esta ruta actualiza el token con el refresh token en formato "json".
POST http://localhost:8080/api/auth/refreshtoken
Content-Type: application/json

{
    "refreshToken": "b50f3cce-bf44-4d95-a418-0ba50abdd754"
}

##### LOGOUT UN USUARIO: esta ruta logout un usuario y borra los refresh tokens.
POST http://localhost:8080/api/auth/signout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2FjaCIsImlhdCI6MTY3OTkwOTc4OSwiZXhwIjoxNjc5OTA5ODg5fQ.PcTOcWdQHJDEcrWveuTfwCJ6wA-1EYh3di8ujFCAAoTPeh33jOP-GL7KxISSoxXgzSFhnqq2pZmiw5_gvCo7hA


##### TEAMS
GET http://localhost:8080/api/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZXJ5MSIsImlhdCI6MTY4MDQ5MjU4MSwiZXhwIjoxNjgwNDkzNTgxfQ.mgj3-sUtfmGED4sJ5uVBufWQlxntSmG8s1rqiUh6QTPEnqHvtGGBxTYa2UYYqIDzahtgLtGMNpSL-tbIoK6R4w
